name: Correr pruebas unitarias, y construccion y push de la imagen

on:
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Ejecución de pruebas unitarias

    steps:
      - name: Configurando Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Correr pruebas unitarias con pytest
        run: |
          cd app
          pytest

  build:
    runs-on: ubuntu-latest
    name: Build y Push a ECR

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v2

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login a Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build y push de la imagen a Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: reto1-digitalnao
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
