name: Unit Testing

on:
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Unit Testing

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v2

      - name: Configurando Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Instalar dependencias
        working-directory: app
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Correr pruebas unitarias con pytest
        working-directory: app
        run: |
          pytest
